services:
  db:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: